apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-buddy-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_YOUR_GITHUB_REPO_URL
    targetRevision: main
    path: week_7/study-buddy-ai/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: study-buddy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
