apiVersion: v1
kind: Service
metadata:
  name: study-buddy-ai-svc
  namespace: study-buddy
spec:
  type: NodePort
  selector:
    app: study-buddy-ai
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30085
